if ~exist("config_run.json", "file")
    error("Please create a config file that specifies the ioconfig file's path.");
end
info_run = jsondecode(fileread("config_run.json"));
filenames_reg_common = fileparts(which("/buildmanagers.m")) + "/reg_common.csv";
filenames_reg = [filenames_reg_common info_run.reg_extension];
runfiles(   info_run.ioconfig_path, ...
            info_run.ioconfig_conv_path, ...
            mode = info_run.mode, ...
            fromidx = info_run.from_idx, ...
            toidx = info_run.to_idx, ...
            filenames_reg = filenames_reg...
            );